### ISSUE TITLE
Forward is not a function when used with react-ssr-prepass

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql-exchange-graphcache#56]
I am using Next.js together with react-ssr-prepass.
I wanted to use this cache in my project. I only replaced the standard cache with this one and did not apply any config. When starting my site, I got the following error: 

```
forward is not a function

TypeError: forward is not a function
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/@urql/exchange-graphcache/dist/urql-exchange-graphcache.js:1038:32
    at _1 (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:46:12)
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:323:14
    at _1 (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:46:12)
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:1072:7
    at _1 (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:46:12)
    at captureTalkback (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:168:10)
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:893:14
    at _1 (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:46:12)
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:1273:7
    at _1 (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:46:12)
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:973:14
    at _1 (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:46:12)
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:933:14
    at _1 (/Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:46:12)
    at /Users/bjoern/projects/Plezzles/frontend/node_modules/wonka/dist/wonka.js:323:14
```

I am using the latest version of `urql-exchange-graphcache` and `urql`

**Comment by JoviDeCroock** [comment]
Did you execute the cache when adding it to your exchanges, `cacheExchange()`? Could you add the way you added it to the client please?

**Comment by BjoernRave** [comment]
Ah, no I did not 😅 Thanks for your help, will close this issue again :)
